server {
    listen 80;
    server_name localhost;

    # Rota para o Frontend (Arquivos estáticos)
    location / {
        root /usr/share/nginx/html;
        index index.html index.html;
        try_files $uri $uri/ /index.html;
    }

    # Rota para processar o formulário RSVP no Backend
    location /rsvp {
        proxy_pass http://backend:3000/rsvp;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded-for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Rotas opcionais para consulta de respostas e resumo
    location /respostas {
        proxy_pass http://backend:3000/respostas;
    }

    location /resumo {
        proxy_pass http://backend:3000/resumo;
    }
}